crew:
  name: 'Aven Support Bot'
  description: 'A multi-agent customer support system for Aven financial services'
  version: '1.0.0'
  
  settings:
    verbose: 1
    process: 'sequential'
    memory: false
    
  llm:
    provider: 'openai'
    model: 'gpt-4o-mini'
    temperature: 0.1
    
  agents:
    - 'router_agent'
    - 'retrieval_agent'
    - 'search_agent'
    - 'response_agent'
    
  tasks:
    - 'routing_task'
    - 'retrieval_task'
    - 'search_task'
    - 'response_task'
    
  tools:
    - 'knowledge_base_search'
    - 'web_search'
    
  environment:
    pinecone_index: 'aven-support-index'
    embedding_model: 'text-embedding-ada-002'
    search_site: 'aven.com'
    top_k: 5 