tools:
  knowledge_base_search:
    name: 'knowledge_base_search'
    description: >
      Search the Aven knowledge base for relevant information.
      This tool searches through the internal documentation and support articles.
    parameters:
      query:
        type: 'string'
        description: 'The search query to process'
        required: true

  web_search:
    name: 'web_search'
    description: >
      Search the web for information about Aven.
      This tool performs a web search when the knowledge base doesn't have sufficient information.
    parameters:
      query:
        type: 'string'
        description: 'The search query to process'
        required: true 